version: "3.5"

services:
  postgres:
    image: "postgres:14.5-alpine"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: "luizalabs_db"
    volumes:
      - ./../../.docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

    networks:
      - luiza-labs-network

  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./../../.docker/prometheus/data:/prometheus
      - ./../../prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      - luiza-labs-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - luiza-labs-network

networks:
  luiza-labs-network:
    driver: bridge