apiVersion: v1
kind: Service
metadata:
  name: luizalabs-service
  namespace: luizalabs
spec:
  selector:
    app: luizalabs-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
