// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/zipcode/service.go

// Package mock is a generated GoMock package.
package mock

import (
	zipcode "luizalabs-technical-test/internal/features/zipcode"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceImp is a mock of ServiceImp interface.
type MockServiceImp struct {
	ctrl     *gomock.Controller
	recorder *MockServiceImpMockRecorder
}

// MockServiceImpMockRecorder is the mock recorder for MockServiceImp.
type MockServiceImpMockRecorder struct {
	mock *MockServiceImp
}

// NewMockServiceImp creates a new mock instance.
func NewMockServiceImp(ctrl *gomock.Controller) *MockServiceImp {
	mock := &MockServiceImp{ctrl: ctrl}
	mock.recorder = &MockServiceImpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceImp) EXPECT() *MockServiceImpMockRecorder {
	return m.recorder
}

// GetAddressByZipCode mocks base method.
func (m *MockServiceImp) GetAddressByZipCode(zipCode string) (*zipcode.GetAddressByZipCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressByZipCode", zipCode)
	ret0, _ := ret[0].(*zipcode.GetAddressByZipCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressByZipCode indicates an expected call of GetAddressByZipCode.
func (mr *MockServiceImpMockRecorder) GetAddressByZipCode(zipCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressByZipCode", reflect.TypeOf((*MockServiceImp)(nil).GetAddressByZipCode), zipCode)
}
