// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/address/{zip-code}": {
            "get": {
                "description": "Get address details using a provided ZIP code. Returns a structured response with address data or error information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Address"
                ],
                "summary": "Retrieve CEP information by ZIP code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ZIP Code",
                        "name": "zip-code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/zipcode.swagGetAddressByZipCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ZIP code format",
                        "schema": {
                            "$ref": "#/definitions/server.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "ZIP code not found",
                        "schema": {
                            "$ref": "#/definitions/server.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/health/ping": {
            "get": {
                "description": "Responds with a \"pong\" message to indicate that the service is healthy.",
                "produces": [
                    "application/json"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.swagHealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.swagHealthResponse": {
            "type": "object"
        },
        "server.APIErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "zipcode.swagGetAddressByZipCodeResponse": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
