name: go-build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  go-build:
    name: Verify, Test, and Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      # linter checks:
      - name: Run Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run Golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./...

      # unit test:
      - name: Run test
        run: |
          go test -v -count=1 ./...

      # smoke test:
      - name: Run Build
        run: |
          docker build -t luizalabs-technical-test -f infra/docker/Dockerfile .
          docker images
