// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/middleware/token_middleware.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenMiddleware is a mock of TokenMiddleware interface.
type MockTokenMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMiddlewareMockRecorder
}

// MockTokenMiddlewareMockRecorder is the mock recorder for MockTokenMiddleware.
type MockTokenMiddlewareMockRecorder struct {
	mock *MockTokenMiddleware
}

// NewMockTokenMiddleware creates a new mock instance.
func NewMockTokenMiddleware(ctrl *gomock.Controller) *MockTokenMiddleware {
	mock := &MockTokenMiddleware{ctrl: ctrl}
	mock.recorder = &MockTokenMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenMiddleware) EXPECT() *MockTokenMiddlewareMockRecorder {
	return m.recorder
}

// Middleware mocks base method.
func (m *MockTokenMiddleware) Middleware() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Middleware")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// Middleware indicates an expected call of Middleware.
func (mr *MockTokenMiddlewareMockRecorder) Middleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Middleware", reflect.TypeOf((*MockTokenMiddleware)(nil).Middleware))
}
